# Installations

In [1]:
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
!dpkg -i cuda-keyring_1.0-1_all.deb

!apt-get update
!apt-get install cuda-12-1

!export CUDA_PATH=/usr/local/cuda-12.1/

--2024-01-25 00:54:49--  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.199.39.144
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.199.39.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4328 (4.2K) [application/x-deb]
Saving to: ‘cuda-keyring_1.0-1_all.deb’

cuda-keyring_1.0-1_ 100%[===================>]   4.23K  --.-KB/s    in 0s      

2024-01-25 00:54:49 (135 MB/s) - ‘cuda-keyring_1.0-1_all.deb’ saved [4328/4328]

(Reading database ... 121658 files and directories currently installed.)
Preparing to unpack cuda-keyring_1.0-1_all.deb ...
Unpacking cuda-keyring (1.0-1) over (1.0-1) ...
Setting up cuda-keyring (1.0-1) ...
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InReleas

In [2]:
!pip3 install  dgl -f https://data.dgl.ai/wheels/cu121/repo.html
!pip3 install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

Looking in links: https://data.dgl.ai/wheels/cu121/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.0/926.0 MB 1.4 MB/s eta 0:00:00
Looking in links: https://data.dgl.ai/wheels-test/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.4/116.4 kB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 43.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.7/526.7 kB 38.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7026 sha256=81b1e66502223f2

In [2]:
!pip3 install dgl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 22.6 MB/s eta 0:00:00


In [3]:
!pip3 install numpy
!pip3 install torch
!pip3 install networkx
!pip3 install matplotlib

!pip3 install wandb -qU

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.4/196.4 kB 19.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.1/254.1 kB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 6.8 MB/s eta 0:00:00


# Initialize Stuff with Auths

In [4]:
# Mount Drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [5]:
# Remove folder
import shutil
shutil.rmtree('/content/adversarial-fraud', ignore_errors=True)

# Reclone
!git clone https://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@github.com/hafizhadi/adversarial-fraud.git

# Append path
import sys
sys.path.append('/content/adversarial-fraud/src')

Cloning into 'adversarial-fraud'...
remote: Enumerating objects: 256, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 256 (delta 152), reused 166 (delta 70), pack-reused 0
Receiving objects: 100% (256/256), 56.99 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (152/152), done.


In [59]:
# WandB
import wandb
wandb.login()

<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:


Abort: 

## Dataset

In [6]:
import torch
import dgl

from dgl.data.utils import makedirs, save_info, load_info
from dgl.sampling import node2vec_random_walk
from sklearn.model_selection import train_test_split
from collections import Counter

DGL backend not selected or invalid.  Assuming PyTorch for now.


Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)


In [7]:
# Load graph and prepare
dataset, _ = dgl.load_graphs('./drive/MyDrive/Academic/Code/Dataset/tfinance/tfinance')
graph = dataset[0]
graph.ndata['label'] = graph.ndata['label'].argmax(1)

graph.ndata['label'] = graph.ndata['label'].long().squeeze(-1)
graph.ndata['feature'] = graph.ndata['feature'].float()

print(f'Graph have {graph.num_nodes()} nodes, {graph.num_edges()} edges')

# SAMPLING
# Randomly get stratified seed nodes
labels = graph.ndata['label']
index = list(range(len(labels)))

idx_sampled, idx_, labels_sampled, labels_ = train_test_split(
    index, labels[index], stratify=labels[index],
    train_size = 0.01, random_state = 777
)

# Random walk from seed
node_trace, edge_trace = node2vec_random_walk(graph, idx_sampled, 1, 1, 10, return_eids=True)
sampled_nodes = list(set(torch.flatten(node_trace).tolist()))
sampled_edges = list(set(torch.flatten(edge_trace).tolist()))

# Get subgraph
graph = dgl.node_subgraph(graph, sampled_nodes)

print(f'Graph have {graph.num_nodes()} nodes, {graph.num_edges()} edges')

Graph have 39357 nodes, 42445086 edges
Graph have 3874 nodes, 3129196 edges


In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
import numpy as np
from numpy import random

sample_size = 10

positives = (graph.ndata['label'] == 1).nonzero().flatten()
sampled = positives[random.choice(list(range(len(positives))), size=sample_size, replace=False)]
new_ids = (torch.Tensor(list(range(len(sampled)))) + graph.num_nodes()).int()
id_dict = dict(zip(sampled.tolist(), new_ids.tolist()))

in_src, in_dst = graph.in_edges(sampled)
out_src, out_dst = graph.out_edges(sampled)

in_dst = torch.from_numpy(np.fromiter((id_dict[i] for i in in_dst.tolist()), int))
out_src = torch.from_numpy(np.fromiter((id_dict[i] for i in out_src.tolist()), int))

graph.ndata['feature'][sampled]

tensor([[5.7000e+01, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 1.0000e+00, 3.5088e-02, 1.7544e-02],
        [4.6000e+02, 1.1300e+02, 0.0000e+00, 2.0000e+00, 4.9000e+01, 3.4000e+01,
         1.1000e+01, 2.5000e+01, 6.3043e-02, 2.1739e-02],
        [4.2000e+02, 3.0000e+00, 0.0000e+00, 2.0000e+00, 0.0000e+00, 2.0000e+00,
         0.0000e+00, 2.0000e+00, 2.3810e-03, 2.3810e-03],
        [7.9400e+02, 1.7000e+01, 0.0000e+00, 1.3000e+01, 0.0000e+00, 1.1000e+01,
         0.0000e+00, 1.1000e+01, 4.7859e-02, 3.4005e-02],
        [1.5740e+03, 9.0000e+00, 0.0000e+00, 9.0000e+00, 0.0000e+00, 7.0000e+00,
         0.0000e+00, 7.0000e+00, 3.6849e-02, 2.0330e-02],
        [4.8000e+01, 2.0700e+02, 0.0000e+00, 2.0000e+00, 1.7500e+02, 4.0000e+00,
         2.0000e+00, 2.0000e+00, 1.6667e-01, 1.0417e-01],
        [4.9500e+02, 1.7380e+03, 3.0000e+00, 8.0000e+00, 1.4560e+03, 6.3000e+01,
         3.8000e+01, 2.8000e+01, 1.7172e-01, 1.2929e-01],
        [5.0000e+02, 1.0200

tensor([3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874, 3874,
        3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875,
        3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875,
        3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875,
        3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875, 3875,
        3875, 3875, 3875, 3875, 3875, 38

tensor([3874., 3875., 3876., 3877., 3878., 3879., 3880., 3881., 3882., 3883.])

## Model

In [127]:
from torch.optim import Adam
from torch.functional import F

import importlib
import experiment_single.supervised_single
import models.benchmarks_supervised
importlib.reload(experiment_single.supervised_single)
importlib.reload(models.benchmarks_supervised)

from experiment_single.supervised_single import BaseExperiment
from models.benchmarks_supervised import GCN

In [128]:
model_config = {
    'model_name': 'GCN',
    'h_feats': 8,
    'num_layers': 2,
    'mlp_h_feats': 8,
    'mlp_num_layers': 2,
    'dropout_rate': 0.1,
    'act_name': "ReLU"

}

train_config = {
    'random_state': 777,
    'train_mode': 'full',
    'batch_size': 128,
    'num_workers': 0,
    'num_epoch': 50,
    'train_ratio': 0.8,
    'test_ratio_from_rest': 0.67,
    'optimizer': Adam,
    'learning_rate': 0.01,
    'loss': F.cross_entropy
}

exp = BaseExperiment(model_config, train_config, graph, verbose=1)

In [129]:
exp.train()

Starting training!
Epoch 0, loss: 23.0345, val mf1: 0.4880, (best 0.4880)
Epoch 1, loss: 14.9248, val mf1: 0.2258, (best 0.4880)
Epoch 2, loss: 11.9354, val mf1: 0.5272, (best 0.5272)
Epoch 3, loss: 12.0076, val mf1: 0.5328, (best 0.5328)
Epoch 4, loss: 8.4157, val mf1: 0.5489, (best 0.5489)
Epoch 5, loss: 10.3637, val mf1: 0.2467, (best 0.5489)
Epoch 6, loss: 8.3759, val mf1: 0.4483, (best 0.5489)
Epoch 7, loss: 7.1637, val mf1: 0.5244, (best 0.5489)
Epoch 8, loss: 7.1471, val mf1: 0.5325, (best 0.5489)
Epoch 9, loss: 6.4780, val mf1: 0.5194, (best 0.5489)
Epoch 10, loss: 4.9757, val mf1: 0.5104, (best 0.5489)
Epoch 11, loss: 5.7029, val mf1: 0.4059, (best 0.5489)
Epoch 12, loss: 4.3524, val mf1: 0.4807, (best 0.5489)
Epoch 13, loss: 4.1130, val mf1: 0.5049, (best 0.5489)
Epoch 14, loss: 4.3160, val mf1: 0.5223, (best 0.5489)
Epoch 15, loss: 3.7020, val mf1: 0.5002, (best 0.5489)
Epoch 16, loss: 3.3048, val mf1: 0.5531, (best 0.5531)
Epoch 17, loss: 2.7867, val mf1: 0.5413, (best 0.55

(0.5650162401964667, 0.7451910408432146)