# Installations

In [ ]:
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
!dpkg -i cuda-keyring_1.0-1_all.deb

!apt-get update
!apt-get install cuda-12-1

!export CUDA_PATH=/usr/local/cuda-12.1/

--2024-01-25 00:54:49--  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.199.39.144
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.199.39.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4328 (4.2K) [application/x-deb]
Saving to: ‘cuda-keyring_1.0-1_all.deb’

cuda-keyring_1.0-1_ 100%[===================>]   4.23K  --.-KB/s    in 0s      

2024-01-25 00:54:49 (135 MB/s) - ‘cuda-keyring_1.0-1_all.deb’ saved [4328/4328]

(Reading database ... 121658 files and directories currently installed.)
Preparing to unpack cuda-keyring_1.0-1_all.deb ...
Unpacking cuda-keyring (1.0-1) over (1.0-1) ...
Setting up cuda-keyring (1.0-1) ...
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InReleas

In [ ]:
!pip3 install  dgl -f https://data.dgl.ai/wheels/cu121/repo.html
!pip3 install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

Looking in links: https://data.dgl.ai/wheels/cu121/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.0/926.0 MB 1.4 MB/s eta 0:00:00
Looking in links: https://data.dgl.ai/wheels-test/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.4/116.4 kB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 43.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.7/526.7 kB 38.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7026 sha256=81b1e66502223f2

In [1]:
!pip3 install dgl
!pip3 install numpy
!pip3 install torch
!pip3 install networkx
!pip3 install matplotlib

!pip3 install wandb -qU

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 22.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.4/195.4 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 257.9/257.9 kB 15.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 9.2 MB/s eta 0:00:00


# Initialize Stuff with Auths

In [1]:
# Mount Drive
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Remove folder
import shutil
shutil.rmtree('/content/adversarial-fraud', ignore_errors=True)

# Reclone
!git clone https://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@github.com/hafizhadi/adversarial-fraud.git

# Append path
import sys
sys.path.append('/content/adversarial-fraud/src')

Cloning into 'adversarial-fraud'...
remote: Enumerating objects: 1439, done.
remote: Counting objects: 100% (296/296), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 1439 (delta 190), reused 287 (delta 181), pack-reused 1143
Receiving objects: 100% (1439/1439), 227.40 KiB | 1.20 MiB/s, done.
Resolving deltas: 100% (904/904), done.


## Dataset

In [3]:
import torch
import dgl

from dgl.data.utils import makedirs, save_info, load_info
from dgl.sampling import node2vec_random_walk
from sklearn.model_selection import train_test_split
from collections import Counter

In [4]:
dataset, _ = dgl.load_graphs('./drive/MyDrive/Academic/Code/Dataset/hetero/yelp')
hetgraph = dataset[0]
hetgraph.is_homogeneous

False

In [5]:

# Load graph and prepare
dataset, _ = dgl.load_graphs('./drive/MyDrive/Academic/Code/Dataset/tfinance/tfinance')
graph = dataset[0]
graph.ndata['label'] = graph.ndata['label'].argmax(1)

graph.ndata['label'] = graph.ndata['label'].long().squeeze(-1)
graph.ndata['feature'] = graph.ndata['feature'].float()

print(f'Graph have {graph.num_nodes()} nodes, {graph.num_edges()} edges')

# SAMPLING
# Randomly get stratified seed nodes
labels = graph.ndata['label']
index = list(range(len(labels)))

idx_sampled, idx_, labels_sampled, labels_ = train_test_split(
    index, labels[index], stratify=labels[index],
    train_size = 0.01, random_state = 777
)

# Random walk from seed
node_trace, edge_trace = node2vec_random_walk(graph, idx_sampled, 1, 1, 10, return_eids=True)
sampled_nodes = list(set(torch.flatten(node_trace).tolist()))
sampled_edges = list(set(torch.flatten(edge_trace).tolist()))

# Get subgraph
graph = dgl.node_subgraph(graph, sampled_nodes)

print(f'Graph have {graph.num_nodes()} nodes, {graph.num_edges()} edges')

Graph have 39357 nodes, 42445086 edges
Graph have 3897 nodes, 2642208 edges


## Model

In [6]:
from torch.optim import Adam
from torch.functional import F

import utils_func
import experiment_multiround.supervised_multi
import models.benchmarks_supervised.simple
import models.benchmarks_supervised.spectral
import models.benchmarks_supervised.h2fd

import importlib
importlib.reload(utils_func)
importlib.reload(experiment_multiround.supervised_multi)
importlib.reload(models.benchmarks_supervised.simple)
importlib.reload(models.benchmarks_supervised.spectral)
importlib.reload(models.benchmarks_supervised.h2fd)

from experiment_multiround.supervised_multi import MultiroundExperiment
from models.benchmarks_supervised.simple import GCN
from models.benchmarks_supervised.spectral import BWGNN
from models.benchmarks_supervised.h2fd import H2FD

In [7]:
model_config = {
    'verbose': 1,
    #'model_name': 'H2F-DETECTOR',
    'model_name': 'GCN',
    'h_feats': 8,
    'num_layers': 2,
    'att_heads': 2,
    'mlp_h_feats': 10,
    'mlp_num_layers': 2,
    'dropout_rate': 0.1,
    'act_name': "ReLU",
}

train_config = {
    'verbose': 1,
    'random_state': 777,
    'train_mode': 'full',
    'batch_size': 128,
    'num_workers': 0,
    'num_epoch': 100,
    'train_ratio': 0.8,
    'test_ratio_from_rest': 0.67,
    'optimizer': Adam,
    'learning_rate': 0.01,
    'loss': F.cross_entropy,
    'round_new_pos': 30,
    'round_new_neg': 900,
    'round_budget_pos': 0,
    'round_budget_neg': 0,
    'round_all_data': False,
    'round_reset_model': False
  }

adver_config = {
    'verbose': 3,
    'adver_name': 'PERTURB-REL',
    'feat_budget': 2,
    'conn_budget': 20,
    'greedy_seed': True
}

In [8]:
exp = MultiroundExperiment(model_config, adver_config, train_config, graph)
for i in range(10):
  exp.adver_round(i)


START - RelativePerturbationAdversary:__init__ | feat_budget: 2,  conn_budget: 20, greedy_seed: True
FINISH - RelativePerturbationAdversary:__init__

STARTING ROUND 0!
Training set: 3117 ({0: 2941, 1: 176}) rows | Validation set:  257 ({0: 243, 1: 14}) rows | Test set:  523 ({0: 493, 1: 30}) rows
Starting training...
Test: REC 13.33 PRE 33.33 MF1 57.83 AUC 57.44
Ending training!
PREDICTION RESULT - DATASET
Dataset - Overall: REC 0.00 PRE 0.00 MF1 48.55 AUC 50.00 TP 0 FP 0 TN 3677 FN 220 | {0: 3677, 1: 220}

STARTING ROUND 1!
START - RelativePerturbationAdversary:generate | n_instances: 30,  return_ids: True, greedy: True
START - BaseAdversary:random_duplicate | n_instances: 30,  label: 1, return_ids: True, prio_pool: [4, 20, 22, 25, 28, 67, 152, 175, 179, 188, 191, 192, 198, 204, 215, 235, 237, 249, 283, 286, 311, 314, 328, 333, 344, 349, 401, 402, 405, 406, 408, 411, 428, 460, 467, 494, 519, 530, 539, 540, 549, 550, 551, 553, 564, 583, 620, 641, 644, 670, 716, 736, 757, 778, 803, 817,

In [46]:
test = exp.dset['graph'].ndata['feature'][:5].clone()
print(test)

feat_coef = 0.2
num_mutated = round(feat_coef * test.shape[1])
idx_mutated = torch.randperm(test.shape[1])[:num_mutated]

for idx in idx_mutated:
  data_mutated = test[:, idx].clone()
  test[:, idx] = data_mutated[torch.randperm(data_mutated.shape[0])]

print(idx_mutated)
print(test)

tensor([[3.0580e+03, 1.1990e+03, 4.1700e+02, 2.1700e+02, 0.0000e+00, 5.8000e+02,
         0.0000e+00, 5.8000e+02, 1.1246e-01, 3.0729e-02],
        [4.6500e+02, 4.9870e+03, 0.0000e+00, 1.3000e+01, 4.8320e+03, 7.0000e+01,
         5.1000e+01, 2.0000e+01, 3.1398e-01, 2.1290e-01],
        [1.4880e+03, 2.0962e+04, 5.4000e+01, 4.9000e+01, 3.3140e+03, 3.5300e+02,
         3.8000e+01, 3.3500e+02, 5.7997e-01, 4.9194e-01],
        [5.0000e+02, 3.1000e+02, 6.0000e+00, 6.0000e+00, 1.8100e+02, 6.4000e+01,
         4.0000e+01, 3.2000e+01, 1.3000e-01, 8.8000e-02],
        [1.8900e+02, 1.4000e+01, 1.0000e+00, 4.0000e+00, 0.0000e+00, 7.0000e+00,
         0.0000e+00, 7.0000e+00, 6.8783e-02, 3.7037e-02]])
tensor([2, 4])
tensor([[3.0580e+03, 1.1990e+03, 0.0000e+00, 2.1700e+02, 3.3140e+03, 5.8000e+02,
         0.0000e+00, 5.8000e+02, 1.1246e-01, 3.0729e-02],
        [4.6500e+02, 4.9870e+03, 4.1700e+02, 1.3000e+01, 0.0000e+00, 7.0000e+01,
         5.1000e+01, 2.0000e+01, 3.1398e-01, 2.1290e-01],
        [1.